name: jk_background_music
version: '1.0-SNAPSHOT'
main: jiekie.BackgroundMusicPlugin
api-version: '1.20'
authors: [Jiekie]
description: 브금 설정 플러그인
commands:
  브금:
    description: 브금 설정 명령어
    usage: /브금
    tab-completer: jiekie.completer.BackgroundMusicTabCompleter