name: jk_background_music
version: '1.0-SNAPSHOT'
main: jiekie.bgm.BackgroundMusicPlugin
api-version: '1.20'
authors: [Jiekie]
description: 브금 설정 플러그인
softdepend:
  - jk_multi_world
commands:
  브금:
    description: 브금 설정 명령어
    usage: /브금
    tab-completer: jiekie.bgm.completer.BackgroundMusicTabCompleter
    permission: jk.background_music.command
    permission-message: ''